### ISSUE TITLE
CI / CD

### ISSUE THREAD

**Issue by ratcomp9992** [soodgarak/soodgarak-BE#10]
## 개요
Github Actions를 사용한 CI / CD 파이프라인을 구축한다.

## TODO
- [ ] docker-compose.yml 작성
- [ ] Github Actions Workflow File 작성
- [x] Github Secrets 추가
