### ISSUE TITLE
음식 리스트 조회 API 구현

### ISSUE THREAD

**Issue by ratcomp9992** [soodgarak/soodgarak-BE#14]
## 개요
Query Parameter에 맞는 데이터 중, 정해진 갯수만큼 랜덤으로 뽑아서 반환하는 기능을 구현한다.

## TODO
- [x] 전체 음식 초기
- [x] 카테고리별 초기
- [x] 검색 키워드별 초기
- [x] 전체 음식 추가
- [x] 카테고리별 추가
- [x] 검색 키워드별 추가
- [x] MBTI별
- [x] 총 데이터 갯수 조회
- [x] 다음 데이터 있는지 체크
