### ISSUE TITLE
공공 데이터 저장

### ISSUE THREAD

**Issue by ratcomp9992** [soodgarak/soodgarak-BE#4]
## 개요
공공 데이터 포털의 OpenAPI를 가져와 데이터를 가공하여 DB에 저장한다.

[조리 식품의 레시피 DB](https://www.data.go.kr/data/15060073/openapi.do)

## TODO
- [x] 필요한 Column 선별
- [x] JSON 데이터 받아오기
- [x] JSON-> String
- [x] String -> Entity
- [x] DB 테이블 생성
  - [x] Recipe 저장
  - [ ] Manual 인덱스 제거
  - [x] Manual 저장
    - [x] 1. List<Manual> allManualList, List<Manual> oneManualList 생성
    - [x] 2. "MANUAL_IMG"로 시작하고, 내용이 null이 아닌 key 탐색
    - [x] 3. recipeId = 레시피 일련번호 기반 탐색해서 가져오기
    - [x] 4. manualId = "MANUAL_IMG" 뒤의 숫자 2개
    - [x] 5. manualImgUrl = value
    - [x] 6. key = manualKey - "_IMG" / manual = value
    - [x] 7. 3,4,6 필드로 Entity 생성 -> of() -> oneManualList에 추가
    - [x] 8. oneManualList 정렬 (manualId 기반 compareTo())
    - [x] 9. 정렬된 oneManualList를 allManualList에 추가
    - [x] 10. recipeRepo.saveAll(allManualList);
---
## 보완할 것
1. String 안거치고 JSON -> VO로 바로 변환해보기
2. DTO, VO를 계속 헷갈림
